function [p_expect,p_covariance] = stabilityIndex_meanLinearisation_zin(f_mean1,f_mean2,f_mean3,mu_mean1,mu_mean2,mu_mean3,P_ank_mean1,P_ank_mean2,P_ank_mean3,P_com_mean1,P_com_mean2,P_com_mean3,f_var1,f_var2,f_var3,mu_var1,mu_var2,mu_var3,P_ank_var1,P_ank_var2,P_ank_var3,P_com_var1,P_com_var2,P_com_var3,m,gz)
%STABILITYINDEX_MEANLINEARISATION_ZIN
%    [P_EXPECT,P_COVARIANCE] = STABILITYINDEX_MEANLINEARISATION_ZIN(F_MEAN1,F_MEAN2,F_MEAN3,MU_MEAN1,MU_MEAN2,MU_MEAN3,P_ANK_MEAN1,P_ANK_MEAN2,P_ANK_MEAN3,P_COM_MEAN1,P_COM_MEAN2,P_COM_MEAN3,F_VAR1,F_VAR2,F_VAR3,MU_VAR1,MU_VAR2,MU_VAR3,P_ANK_VAR1,P_ANK_VAR2,P_ANK_VAR3,P_COM_VAR1,P_COM_VAR2,P_COM_VAR3,M,GZ)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    25-Sep-2014 10:09:23

t2 = gz.*m;
t3 = f_mean3+t2;
t4 = 1.0./t3;
t5 = conj(f_mean3);
t6 = t2+t5;
t7 = conj(P_ank_mean1);
t8 = P_ank_mean3.*f_mean1;
t17 = P_ank_mean1.*f_mean3;
t18 = P_com_mean1.*gz.*m;
t9 = mu_mean2+t8-t17-t18;
t10 = 1.0./t6;
t11 = conj(P_ank_mean3);
t12 = conj(f_mean1);
t13 = 1.0./t6.^2;
t14 = conj(P_ank_mean2);
t15 = P_ank_mean1.*t4;
t16 = 1.0./t3.^2;
t19 = t9.*t16;
t20 = t15+t19;
t21 = conj(f_mean2);
t22 = t7.*t10;
t23 = conj(mu_mean2);
t24 = t11.*t12;
t25 = conj(P_com_mean1);
t26 = t23+t24-t5.*t7-gz.*m.*t25;
t27 = t13.*t26;
t28 = t22+t27;
t29 = P_ank_mean3.*f_mean2;
t39 = P_ank_mean2.*f_mean3;
t40 = P_com_mean2.*gz.*m;
t30 = mu_mean1+t29-t39-t40;
p_expect = [-t4.*t9;-t4.*t30];
if nargout > 1
    t31 = t10.*t14;
    t32 = conj(mu_mean1);
    t33 = t11.*t21;
    t34 = conj(P_com_mean2);
    t35 = t32+t33-t5.*t14-gz.*m.*t34;
    t36 = t13.*t35;
    t37 = t31+t36;
    t38 = P_ank_mean2.*t4;
    t41 = t16.*t30;
    t42 = t38+t41;
    t43 = gz.^2;
    t44 = m.^2;
    p_covariance = reshape([f_var3.*t20.*t28+mu_var2.*t4.*t10+P_ank_var1.*f_mean3.*t4.*t5.*t10+P_ank_var3.*f_mean1.*t4.*t10.*t12+P_ank_mean3.*f_var1.*t4.*t10.*t11+P_com_var1.*t4.*t10.*t43.*t44,f_var3.*t28.*t42+P_ank_var3.*f_mean2.*t4.*t10.*t12,f_var3.*t20.*t37+P_ank_var3.*f_mean1.*t4.*t10.*t21,f_var3.*t37.*t42+mu_var1.*t4.*t10+P_ank_var2.*f_mean3.*t4.*t5.*t10+P_ank_var3.*f_mean2.*t4.*t10.*t21+P_ank_mean3.*f_var2.*t4.*t10.*t11+P_com_var2.*t4.*t10.*t43.*t44],[2, 2]);
end
