function dh = outputDerivatives(Xhat, model)
   
dh = rigidBodyOutputsDerivatives(...
        Xhat(1) ,Xhat(2) ,Xhat(3),...
        Xhat(4) ,Xhat(5) ,Xhat(6),...
        Xhat(7) ,Xhat(8) ,Xhat(9),...
        Xhat(10),Xhat(11),Xhat(12),...
        Xhat(13),Xhat(14),Xhat(15),...
        model.I(1,1),model.I(2,2),model.I(3,3),model.m,model.g);