function [pcop_expect,pcop_covariance] = computeCOP(muc_x_mean,muc_y_mean,fc_z_mean,muc_x_var,muc_y_var,fc_z_var)
%COMPUTECOP
%    [PCOP_EXPECT,PCOP_COVARIANCE] = COMPUTECOP(MUC_X_MEAN,MUC_Y_MEAN,FC_Z_MEAN,MUC_X_VAR,MUC_Y_VAR,FC_Z_VAR)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    04-Mar-2015 15:23:23

t2 = 1.0./fc_z_mean;
pcop_expect = [-muc_x_mean.*t2;muc_y_mean.*t2];
if nargout > 1
    t3 = 1.0./fc_z_mean.^4;
    t4 = 1.0./fc_z_mean.^2;
    pcop_covariance = reshape([muc_x_var.*t4+fc_z_var.*muc_x_mean.^2.*t3,-fc_z_var.*muc_x_mean.*muc_y_mean.*t3,-fc_z_var.*muc_x_mean.*muc_y_mean.*t3,muc_y_var.*t4+fc_z_var.*muc_y_mean.^2.*t3],[2, 2]);
end
