function plotResultsOutput_withSkin(dataBaseFolder,filter,XUpt, XPred,P, tK, yM,source)

if(nargin<3)
    load(strcat(dataBaseFolder,'filteredResult.mat'));
    tK = tKalman;
    yM = yMeas;
    source = 2;
    XUpt = Xupdt;
    XPred = Xhat;
%     sysX = sys;
    tMin = tK(1);
end

idx = 1;

% wrench above foot
% stateVar = 7:12;
stateVar = [7;10;8;11;9;12]; %proper ordering for proper visualization as subplots
pT.titleText = {'Expectation of force f_o',...
    'Expectation of Moment u_o',...
    '',...
    '',...
    '',...
    ''
    };
pT.xlabelText = {'Time t(sec)',...
    'Time t(sec)',...
    'Time t(sec)',...
    'Time t(sec)',...
    'Time t(sec)',...
    'Time t(sec)'
    };
pT.ylabelText = {'E(f_x) N',...
    'E(u_x) Nm',...
    'E(f_y) N',...
    'E(u_y) Nm',...
    'E(f_z) N'....
    'E(u_z) Nm'
    };
cols = {'b','b','g','g','r','r'};
plotFilterResultTimeSeries(tK(idx:end),XUpt(idx:end,:),yM(idx:end,:),P(:,:,idx:end),stateVar,pT,cols,[3,2]);%,sys(idx:end,:));

% wrench below foot
% stateVar = 13:18;
stateVar = [13;16;14;17;15;18];
pT.titleText = {'Expectation of force f_c',...
    'Expectation of Moment u_c',...
    '',...
    '',...
    '',...
    ''
    };
cols = {'b','b','g','g','r','r'};
plotFilterResultTimeSeries(tK(idx:end),XUpt(idx:end,:),yM(idx:end,:),P(:,:,idx:end),stateVar,pT,cols,[3,2]);%,sys(idx:end,:));


% velocities
% stateVar = 1:6;
stateVar = [1;4;2;5;3;6];
pT.titleText = {'Expectation of Translation Velocity v_B',...
    'Expectation of Angular Velocity \omega_B',...
    '',...
    '',...
    '',...
    ''
    };
pT.ylabelText = {'E(v_B_x) m/sec',...
    'E(\omega_B_x) rad/sec',...
    'E(v_B_y) N',...
    'E(\omega_B_y) m/sec',...
    'E(v_B_z) N'....
    'E(\omega_B_z) rad/sec'
    };
cols = {'b','b','g','g','r','r'};
%plotFilterResultTimeSeries(tK(idx:end),XUpt(idx:end,:),yM(idx:end,:),P(:,:,idx:end),stateVar,pT,cols,[3,2]);
plotFilterResultTimeSeries(tK(idx:end),XUpt(idx:end,:),[],P(:,:,idx:end),stateVar,pT,cols,[3,2]);%,sys(idx:end,:));

% orientation
stateVar = 19:21;
pT.titleText = {'Expectation of Orientation',...
    '',...
    '',...
    ''
    };
pT.ylabelText = {'E(\phi_x) degs',...
    'E(\phi_y) degs',...
    'E(\phi_z) degs'
    };
cols = {'b','g','r'};
plotFilterResultTimeSeries(tK(idx:end),rad2deg(XUpt(idx:end,:)),[],P(:,:,idx:end),stateVar,pT,cols,[]);%,sys(idx:end,:));

%% Params
if(strcmp(filter,'jekf') == 1 || strcmp(filter,'dekf') == 1)
    
    stateVar = [22;25;23;26;24;27];
    
pT.titleText = {'Expectation of Stiffness K_B',...
    'Expectation of Damping C_B',...
    '',...
    '',...
    '',...
    ''
    };
pT.ylabelText = {'E(k_B_x) ',...
    'E(c_B_x) ',...
    'E(k_B_y) ',...
    'E(c_B_y) ',...
    'E(k_B_z) '....
    'E(c_B_z) '
    };
cols = {'b','b','g','g','r','r'};
    plotFilterResultTimeSeries(tK(idx:end),XUpt(idx:end,:),[],P(:,:,idx:end),stateVar,pT,cols,[3,2]);%,sys(idx:end,:));
    
    
end
% FRI
% if(source==2)
%      plot_FRI(XUpt,P,XPred, P,tK, idx,length(tK));%,'b',index+5+figPreN);
%  end


end
