function [p_expect,p_covariance] = stabilityIndex_arbitrayLinearisation_zin(f_bar1,f_bar2,f_bar3,mu_bar1,mu_bar2,mu_bar3,P_ank_bar1,P_ank_bar2,P_ank_bar3,P_com_bar1,P_com_bar2,P_com_bar3,f_mean1,f_mean2,f_mean3,mu_mean1,mu_mean2,mu_mean3,P_ank_mean1,P_ank_mean2,P_ank_mean3,P_com_mean1,P_com_mean2,P_com_mean3,f_var1,f_var2,f_var3,mu_var1,mu_var2,mu_var3,P_ank_var1,P_ank_var2,P_ank_var3,P_com_var1,P_com_var2,P_com_var3,m,gz)
%STABILITYINDEX_ARBITRAYLINEARISATION_ZIN
%    [P_EXPECT,P_COVARIANCE] = STABILITYINDEX_ARBITRAYLINEARISATION_ZIN(F_BAR1,F_BAR2,F_BAR3,MU_BAR1,MU_BAR2,MU_BAR3,P_ANK_BAR1,P_ANK_BAR2,P_ANK_BAR3,P_COM_BAR1,P_COM_BAR2,P_COM_BAR3,F_MEAN1,F_MEAN2,F_MEAN3,MU_MEAN1,MU_MEAN2,MU_MEAN3,P_ANK_MEAN1,P_ANK_MEAN2,P_ANK_MEAN3,P_COM_MEAN1,P_COM_MEAN2,P_COM_MEAN3,F_VAR1,F_VAR2,F_VAR3,MU_VAR1,MU_VAR2,MU_VAR3,P_ANK_VAR1,P_ANK_VAR2,P_ANK_VAR3,P_COM_VAR1,P_COM_VAR2,P_COM_VAR3,M,GZ)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    25-Sep-2014 10:09:21

t2 = gz.*m;
t3 = f_bar3+t2;
t4 = 1.0./t3;
t5 = P_ank_bar3.*f_bar1;
t9 = P_ank_bar1.*f_bar3;
t10 = P_com_bar1.*gz.*m;
t6 = mu_bar2+t5-t9-t10;
t7 = P_ank_bar1.*t4;
t8 = 1.0./t3.^2;
t11 = t6.*t8;
t12 = t7+t11;
t13 = P_ank_bar3.*f_bar2;
t16 = P_ank_bar2.*f_bar3;
t17 = P_com_bar2.*gz.*m;
t14 = mu_bar1+t13-t16-t17;
t15 = P_ank_bar2.*t4;
t18 = t8.*t14;
t19 = t15+t18;
p_expect = [f_bar3.*t12+f_mean3.*t12-mu_bar2.*t4-mu_mean2.*t4-t4.*t6+P_ank_bar1.*f_bar3.*t4-P_ank_bar3.*f_bar1.*t4.*2.0+P_ank_mean1.*f_bar3.*t4-P_ank_mean3.*f_bar1.*t4-P_ank_bar3.*f_mean1.*t4+P_com_bar1.*gz.*m.*t4+P_com_mean1.*gz.*m.*t4;f_bar3.*t19+f_mean3.*t19-mu_bar1.*t4-mu_mean1.*t4-t4.*t14+P_ank_bar2.*f_bar3.*t4-P_ank_bar3.*f_bar2.*t4.*2.0+P_ank_mean2.*f_bar3.*t4-P_ank_mean3.*f_bar2.*t4-P_ank_bar3.*f_mean2.*t4+P_com_bar2.*gz.*m.*t4+P_com_mean2.*gz.*m.*t4];
if nargout > 1
    t20 = conj(f_bar3);
    t21 = t2+t20;
    t22 = conj(P_ank_bar1);
    t23 = 1.0./t21;
    t24 = conj(P_ank_bar3);
    t25 = conj(f_bar1);
    t26 = 1.0./t21.^2;
    t27 = conj(P_ank_bar2);
    t28 = conj(f_bar2);
    t29 = t22.*t23;
    t30 = conj(mu_bar2);
    t31 = t24.*t25;
    t32 = conj(P_com_bar1);
    t33 = t30+t31-t20.*t22-gz.*m.*t32;
    t34 = t26.*t33;
    t35 = t29+t34;
    t36 = t23.*t27;
    t37 = conj(mu_bar1);
    t38 = t24.*t28;
    t39 = conj(P_com_bar2);
    t40 = t37+t38-t20.*t27-gz.*m.*t39;
    t41 = t26.*t40;
    t42 = t36+t41;
    t43 = gz.^2;
    t44 = m.^2;
    p_covariance = reshape([f_var3.*t12.*t35+mu_var2.*t4.*t23+P_ank_var1.*f_bar3.*t4.*t20.*t23+P_ank_var3.*f_bar1.*t4.*t23.*t25+P_ank_bar3.*f_var1.*t4.*t23.*t24+P_com_var1.*t4.*t23.*t43.*t44,f_var3.*t19.*t35+P_ank_var3.*f_bar2.*t4.*t23.*t25,f_var3.*t12.*t42+P_ank_var3.*f_bar1.*t4.*t23.*t28,f_var3.*t19.*t42+mu_var1.*t4.*t23+P_ank_var2.*f_bar3.*t4.*t20.*t23+P_ank_var3.*f_bar2.*t4.*t23.*t28+P_ank_bar3.*f_var2.*t4.*t23.*t24+P_com_var2.*t4.*t23.*t43.*t44],[2, 2]);
end
